from typing import Any, Iterable, Iterator, Protocol


class MetaDataProtocol(Protocol):
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...

    def keys(self) -> Iterable[str]: ...

    def to_text(self) -> str: ...
